# CMake generated Testfile for 
# Source directory: /home/lucas/uni/363/ray_tracer/libraries/glm/test/ext
# Build directory: /home/lucas/uni/363/ray_tracer/libraries/glm/test/ext
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test-ext_matrix_relational "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_matrix_relational")
add_test(test-ext_matrix_transform "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_matrix_transform")
add_test(test-ext_matrix_common "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_matrix_common")
add_test(test-ext_matrix_int2x2_sized "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_matrix_int2x2_sized")
add_test(test-ext_matrix_int2x3_sized "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_matrix_int2x3_sized")
add_test(test-ext_matrix_int2x4_sized "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_matrix_int2x4_sized")
add_test(test-ext_matrix_int3x2_sized "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_matrix_int3x2_sized")
add_test(test-ext_matrix_int3x3_sized "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_matrix_int3x3_sized")
add_test(test-ext_matrix_int3x4_sized "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_matrix_int3x4_sized")
add_test(test-ext_matrix_int4x2_sized "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_matrix_int4x2_sized")
add_test(test-ext_matrix_int4x3_sized "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_matrix_int4x3_sized")
add_test(test-ext_matrix_int4x4_sized "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_matrix_int4x4_sized")
add_test(test-ext_matrix_uint2x2_sized "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_matrix_uint2x2_sized")
add_test(test-ext_matrix_uint2x3_sized "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_matrix_uint2x3_sized")
add_test(test-ext_matrix_uint2x4_sized "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_matrix_uint2x4_sized")
add_test(test-ext_matrix_uint3x2_sized "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_matrix_uint3x2_sized")
add_test(test-ext_matrix_uint3x3_sized "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_matrix_uint3x3_sized")
add_test(test-ext_matrix_uint3x4_sized "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_matrix_uint3x4_sized")
add_test(test-ext_matrix_uint4x2_sized "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_matrix_uint4x2_sized")
add_test(test-ext_matrix_uint4x3_sized "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_matrix_uint4x3_sized")
add_test(test-ext_matrix_uint4x4_sized "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_matrix_uint4x4_sized")
add_test(test-ext_quaternion_common "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_quaternion_common")
add_test(test-ext_quaternion_exponential "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_quaternion_exponential")
add_test(test-ext_quaternion_geometric "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_quaternion_geometric")
add_test(test-ext_quaternion_relational "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_quaternion_relational")
add_test(test-ext_quaternion_transform "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_quaternion_transform")
add_test(test-ext_quaternion_trigonometric "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_quaternion_trigonometric")
add_test(test-ext_quaternion_type "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_quaternion_type")
add_test(test-ext_scalar_common "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_scalar_common")
add_test(test-ext_scalar_constants "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_scalar_constants")
add_test(test-ext_scalar_int_sized "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_scalar_int_sized")
add_test(test-ext_scalar_uint_sized "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_scalar_uint_sized")
add_test(test-ext_scalar_integer "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_scalar_integer")
add_test(test-ext_scalar_ulp "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_scalar_ulp")
add_test(test-ext_scalar_relational "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_scalar_relational")
add_test(test-ext_vec1 "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_vec1")
add_test(test-ext_vector_bool1 "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_vector_bool1")
add_test(test-ext_vector_common "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_vector_common")
add_test(test-ext_vector_iec559 "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_vector_iec559")
add_test(test-ext_vector_int1_sized "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_vector_int1_sized")
add_test(test-ext_vector_int2_sized "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_vector_int2_sized")
add_test(test-ext_vector_int3_sized "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_vector_int3_sized")
add_test(test-ext_vector_int4_sized "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_vector_int4_sized")
add_test(test-ext_vector_integer "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_vector_integer")
add_test(test-ext_vector_integer_sized "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_vector_integer_sized")
add_test(test-ext_vector_uint1_sized "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_vector_uint1_sized")
add_test(test-ext_vector_uint2_sized "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_vector_uint2_sized")
add_test(test-ext_vector_uint3_sized "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_vector_uint3_sized")
add_test(test-ext_vector_uint4_sized "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_vector_uint4_sized")
add_test(test-ext_vector_relational "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_vector_relational")
add_test(test-ext_vector_ulp "/home/lucas/uni/363/ray_tracer/libraries/glm/test/ext/test-ext_vector_ulp")
